export default {
  Ungrouped: [
    "cohort",
    "fromCohort",
    "tumorClass",
    "Age",
    "Sex",
    "consent_race",
    "Vital status",
    "hypertension",
    "grade",
    "BMI",
    "Weight_at_surgery",
    "alcohol_consumption",
    "smoking_history",
    "Country",
    "Stage",
    "methyl_type2",
    "im_type",
    "im_type_discovery",
  ],
  Mutation: [
    "BAP1",
    "FLCN",
    "MET",
    "MTOR",
    "PBRM1",
    "SETD2",
    "TP53",
    "TSC1",
    "TSC2",
    "VHL",
    "CCND1",
  ],
  Chromosome_gain: ["gain_chr7", "gain_chr17"],
  Chromosome_loss: ["loss_chr1", "loss_chr3p", "loss_chr14q"],
  Numerical: ["purity", "ploidy", "wgii"],
};
